### ISSUE TITLE
AbstractStyleSheet + MediaQuery

### ISSUE THREAD

**Issue by marcioendo** [objectos/css#34]
Something similar to what was discussed here #9 

```java
public class Grid extends AbstractStyleSheet {
  public static final ClassSelector container = cn("container");

  private final Breakpoints breakpoints;
  
  public Grid(Breakpoints breakpoints) {
    this.breakpoints = breakpoints;
  }

  @Override
  protected final void defintion() {
    style(
        container,
        margin(zero(), auto),        
    );

    media(breakpoints.tablet());

    style(
        container,
        maxWidth(px(720)),
        padding(zero())
    );

    media(breakpoints.desktop());

    style(
        container,
        maxWidth(px(960))
    );
  }
}
```

Would generate:

```css
.container {
  margin: 0 auto;
}

@media screen and (min-width: 768px) {
  .container {
    max-width: 720px;
    padding: 0;
  }
}

@media screen and (min-width: 992px) {
  .container {
    max-width: 960px;
  }
}
```
